name: 'zstu-report'
description: 'do zstu daily report'
inputs:
  username:
    description: 'your zstu sso username/student number'
    required: true
    default: 'default'
  password:
    description: 'your zstu sso password'
    required: true
    default: 'default'
  location:
    description: 'your current living city'
    required: false
    default: '浙江省 杭州市 钱塘区'
  notify:
    description: 'your notify id'
    required: false
    default: ''
  retries:
    description: 'maximum retry number'
    required: false
    default: 0
outputs:
  message: # id of output
    description: 'The return of the execution'
runs:
  using: 'docker'
  image: 'typenoob/zstu_report'
  args:
    - ${{ inputs.username }}
    - ${{ inputs.password }}
    - ${{ inputs.location }}
    - ${{ inputs.notify }}
    - ${{ inputs.retries }}
