on: 
  workflow_dispatch:

jobs:
  zstu-daily-report-job:
    runs-on: ubuntu-latest
    name: A job to do zstu daily report
    steps:
      - name: Run
        id: report
        uses: CodelabLearning/zstu_report@master
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Get the return
        run: echo "The result was ${{ steps.report.outputs.message }}"
